import {
  Breadcrumb,
  BreadcrumbList,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbSeparator,
  BreadcrumbPage,
} from '@/components/ui/breadcrumb';
import { Badge } from '@/components/ui/badge';
import { SidebarTrigger } from '@/components/ui/sidebar';
import { Separator } from '@/components/ui/separator';
import { Button } from '@/components/ui/button';

export default function Home() {
  return (
    <>
      <header className='flex h-16 shrink-0 items-center gap-2 border-b px-4'>
        <SidebarTrigger className='-ml-1' />
        <Separator
          orientation='vertical'
          className='mr-2 data-[orientation=vertical]:h-4'
        />
        <Breadcrumb>
          <BreadcrumbList>
            <BreadcrumbItem className='hidden md:block'>
              <BreadcrumbPage>Dashboard</BreadcrumbPage>
            </BreadcrumbItem>
          </BreadcrumbList>
        </Breadcrumb>
      </header>
      <main className='min-h-screen lg:max-w-7xl bg-white px-8 py-10'>
        <div className='flex justify-between items-center mb-8'>
          <div>
            <h1 className='text-2xl font-bold mb-1'>Dashboard</h1>
            <p className='text-gray-500 text-base'>Recent generated reports</p>
          </div>
          <Button className='bg-black text-white'>Generate New Report</Button>
        </div>
        <div className='bg-white rounded-lg border p-0 overflow-x-auto'>
          <table className='min-w-full text-sm'>
            <thead className='bg-gray-50'>
              <tr>
                <th className='px-6 py-4 text-left font-semibold text-gray-500'>
                  Client
                </th>
                <th className='px-6 py-4 text-left font-semibold text-gray-500'>
                  Status
                </th>
                <th className='px-6 py-4 text-left font-semibold text-gray-500'>
                  Generated By
                </th>
                <th className='px-6 py-4 text-left font-semibold text-gray-500'>
                  Date Generated
                </th>
                <th className='px-6 py-4 text-left font-semibold text-gray-500'>
                  Report
                </th>
                <th className='px-6 py-4'></th>
              </tr>
            </thead>
            <tbody>
              {/* Example rows, replace with dynamic data as needed */}
              <tr className='border-t'>
                <td className='px-6 py-4'>Digital Marketing Pro</td>
                <td className='px-6 py-4'>
                  <Badge variant='default'>Ready</Badge>
                </td>
                <td className='px-6 py-4'>Sarah Johnson</td>
                <td className='px-6 py-4'>Aug 12, 2025</td>
                <td className='px-6 py-4'>
                  <a href='#' className='text-blue-600 underline'>
                    dmpro-100003082025-re...
                  </a>
                </td>
                <td className='px-6 py-4 text-right'>•••</td>
              </tr>
              <tr className='border-t'>
                <td className='px-6 py-4'>TechCorp Solutions</td>
                <td className='px-6 py-4'>
                  <Badge variant='secondary'>
                    <span className='animate-spin inline-block w-3 h-3 border-2 border-gray-400 border-t-transparent rounded-full'></span>
                    In Process
                  </Badge>
                </td>
                <td className='px-6 py-4'>Sarah Johnson</td>
                <td className='px-6 py-4'>Aug 12, 2025</td>
                <td className='px-6 py-4'>-</td>
                <td className='px-6 py-4 text-right'>•••</td>
              </tr>
              <tr className='border-t'>
                <td className='px-6 py-4'>Digital Marketing Pro</td>
                <td className='px-6 py-4'>
                  <Badge variant='destructive'>Failed</Badge>
                </td>
                <td className='px-6 py-4'>Sarah Johnson</td>
                <td className='px-6 py-4'>Aug 12, 2025</td>
                <td className='px-6 py-4'>-</td>
                <td className='px-6 py-4 text-right'>•••</td>
              </tr>
              <tr className='border-t'>
                <td className='px-6 py-4'>Digital Marketing Pro</td>
                <td className='px-6 py-4'>
                  <Badge variant='destructive'>Failed</Badge>
                </td>
                <td className='px-6 py-4'>Sarah Johnson</td>
                <td className='px-6 py-4'>Aug 12, 2025</td>
                <td className='px-6 py-4'>-</td>
                <td className='px-6 py-4 text-right'>•••</td>
              </tr>
            </tbody>
          </table>
        </div>
      </main>
    </>
  );
}
